states:
  Origin:         { impl: patterns.origin.Origin }
  Pulse:          { impl: patterns.pulse.Pulse }
  Formulation:    { impl: patterns.formulation.Formulation }
  Proliferation:  { impl: patterns.proliferation.Proliferation }
  Pruning:        { impl: patterns.pruning.Pruning }
  Awareness:      { impl: patterns.awareness.Awareness }
  Persistence:    { impl: patterns.persistence.Persistence }
  Representation: { impl: patterns.representation.Representation }
  Memory:         { impl: patterns.memory.Memory }
  Imprint:        { impl: patterns.imprint.Imprint }

flows:
  - { from: Origin, to: Pulse }
  - { from: Pulse, to: Formulation }
  - { from: Formulation, to: Proliferation }
  - { from: Proliferation, to: Pruning }
  - { from: Pruning, to: Awareness }
  - { from: Awareness, to: Memory }
  - { from: Memory, to: Imprint }
